// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALUjakZY2oGC_4voVR8eu9PBoEIIvJh7k',
    appId: '1:892229345597:web:39b4871f40371c36596554',
    messagingSenderId: '892229345597',
    projectId: 'mynotes-flutter1092',
    authDomain: 'mynotes-flutter1092.firebaseapp.com',
    storageBucket: 'mynotes-flutter1092.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFSbUGt7rhvNhz7ux1U9FETUj3zQpEVZw',
    appId: '1:892229345597:android:5ee15514aaf18b79596554',
    messagingSenderId: '892229345597',
    projectId: 'mynotes-flutter1092',
    storageBucket: 'mynotes-flutter1092.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB9bk22QWBYcGodFWfOI9VeQTQsKB6V7w',
    appId: '1:892229345597:ios:849ea489a988d361596554',
    messagingSenderId: '892229345597',
    projectId: 'mynotes-flutter1092',
    storageBucket: 'mynotes-flutter1092.appspot.com',
    iosClientId: '892229345597-tbp8rcadpu9s8cu9bi5kmaqvt3f0kqqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB9bk22QWBYcGodFWfOI9VeQTQsKB6V7w',
    appId: '1:892229345597:ios:849ea489a988d361596554',
    messagingSenderId: '892229345597',
    projectId: 'mynotes-flutter1092',
    storageBucket: 'mynotes-flutter1092.appspot.com',
    iosClientId: '892229345597-tbp8rcadpu9s8cu9bi5kmaqvt3f0kqqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
